// src/pages/inventory/IssueForm.jsx
import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  Card, Form, Input, Select, Button, InputNumber,
  Row, Col, Space, Typography, message
} from 'antd'
import { SaveOutlined } from '@ant-design/icons'
import { useQuery, useMutation, useQueryClient } from '@tanstack/react-query'
import { supabase } from '../../lib/supabase'
import { useOrganization } from '../../contexts/OrganizationContext'
import { useScope } from '../../contexts/ScopeContext'
import { useTheme } from '../../contexts/ThemeContext'
import dayjs from 'dayjs'

const { Title } = Typography
const { Option } = Select

const IssueForm = () => {
  const navigate = useNavigate()
  const { org } = useOrganization()
  const { selectedBranch, selectedFinancialYear } = useScope()
  const { theme } = useTheme()
  const primaryColor = theme?.primary_color || '#0D47A1'
  const [form] = Form.useForm()
  const queryClient = useQueryClient()

  const [selectedItem, setSelectedItem] = useState(null)

  // Fetch active inventory items
  const { data: inventoryItems } = useQuery({
    queryKey: ['inventory-items-active', org?.id],
    queryFn: async () => {
      if (!org?.id) return []
      const { data, error } = await supabase
        .from('inventory_items')
        .select('id, item_name, unit_price, unit')
        .eq('organization_id', org.id)
        .eq('is_active', true)
        .order('item_name')
      if (error) throw error
      return data || []
    },
    enabled: !!org?.id,
  })

  // Fetch students (optional)
  const { data: students } = useQuery({
    queryKey: ['students-dropdown', org?.id],
    queryFn: async () => {
      if (!org?.id) return []
      const { data, error } = await supabase
        .from('students')
        .select('id, first_name, last_name')
        .eq('organization_id', org.id)
        .order('first_name')
      if (error) throw error
      return data || []
    },
    enabled: !!org?.id,
  })

  const createMutation = useMutation({
    mutationFn: async (values) => {
      // total_amount is auto‑generated by the database (quantity * unit_price)
      const payload = {
        item_id: values.item_id,
        transaction_type: 'issue',
        quantity: values.quantity,
        unit_price: values.unit_price,
        reference: values.reference || '',
        notes: values.notes || '',
        branch_id: selectedBranch?.id || null,
        financial_year_id: selectedFinancialYear?.id || null,
        organization_id: org.id,
        student_id: values.student_id || null,
      }
      const { error } = await supabase.from('inventory_transactions').insert(payload)
      if (error) throw error
    },
    onSuccess: () => {
      message.success('Inventory issued successfully')
      queryClient.invalidateQueries(['inventory-transactions'])
      navigate('/inventory/transactions')
    },
    onError: (err) => message.error(err.message),
  })

  const handleItemChange = (itemId) => {
    const item = inventoryItems?.find(i => i.id === itemId)
    setSelectedItem(item)
    if (item) {
      form.setFieldsValue({
        unit_price: item.unit_price,
        unit: item.unit,
      })
    }
  }

  return (
    <div style={{ padding: 8, maxWidth: 600, margin: '0 auto' }}>
      <Title level={4} style={{ color: primaryColor }}>Issue Inventory Item</Title>
      <Form
        form={form}
        layout="vertical"
        onFinish={(values) => createMutation.mutate(values)}
        initialValues={{ quantity: 1 }}
      >
        <Card bordered={false} style={{ borderTop: `4px solid ${primaryColor}`, marginBottom: 16 }}>
          <Form.Item name="item_id" label="Item" rules={[{ required: true }]}>
            <Select
              showSearch
              placeholder="Select item"
              onChange={handleItemChange}
              filterOption={(input, option) => option.children.toLowerCase().includes(input.toLowerCase())}
            >
              {inventoryItems?.map(item => (
                <Option key={item.id} value={item.id}>{item.item_name}</Option>
              ))}
            </Select>
          </Form.Item>

          <Row gutter={16}>
            <Col span={8}>
              <Form.Item name="quantity" label="Quantity" rules={[{ required: true }]}>
                <InputNumber min={1} style={{ width: '100%' }} />
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="unit_price" label="Unit Price (Cost)" rules={[{ required: true }]}>
                <InputNumber min={0} step={0.01} style={{ width: '100%' }} />
              </Form.Item>
            </Col>
            <Col span={8}>
              <Form.Item name="unit" label="Unit">
                <Input disabled />
              </Form.Item>
            </Col>
          </Row>

          <Form.Item name="student_id" label="Issue to Student (optional)">
            <Select placeholder="Select student" allowClear showSearch optionFilterProp="children">
              {students?.map(s => (
                <Option key={s.id} value={s.id}>{s.first_name} {s.last_name}</Option>
              ))}
            </Select>
          </Form.Item>

          <Form.Item name="reference" label="Reference">
            <Input />
          </Form.Item>
          <Form.Item name="notes" label="Notes">
            <Input.TextArea rows={2} />
          </Form.Item>
        </Card>

        <Space>
          <Button
            type="primary"
            htmlType="submit"
            icon={<SaveOutlined />}
            loading={createMutation.isLoading}
            style={{ backgroundColor: primaryColor, borderColor: primaryColor }}
          >
            Issue Item
          </Button>
          <Button onClick={() => navigate('/inventory/transactions')}>Cancel</Button>
        </Space>
      </Form>
    </div>
  )
}

export default IssueForm